version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: sierra.morehardt
      POSTGRES_PASSWORD: Test123!
      POSTGRES_DB: happyfeet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      # Force rebuild of bcrypt in development
      args:
        - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      # Don't mount node_modules to avoid permission issues
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://sierra.morehardt:Test123!@db:5432/happyfeet
      PORT: 8080
    ports:
      - "8080:8080"
    # Uncomment the following if you want to wait for db to be ready
    # command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "dev"]
    # Use nodemon for development
    command: sh -c "npm rebuild bcrypt --build-from-source && npm run dev"

volumes:
  db_data:
